import math

import torch


def _get_audio_frames(audio):
    waveform = audio["waveform"]
    if hasattr(waveform, "detach"):
        waveform = waveform.detach().cpu()
    waveform = torch.as_tensor(waveform)
    if waveform.ndim == 3:
        return int(waveform.shape[-1])
    if waveform.ndim == 2:
        return int(waveform.shape[-1])
    if waveform.ndim == 1:
        return int(waveform.shape[0])
    raise ValueError(f"Unsupported audio waveform shape: {tuple(waveform.shape)}")


class AFLAudioLoopCalculator:
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "audio": ("AUDIO",),
                "fps": ("FLOAT", {
                    "default": 25.0,
                    "min": 0.001,
                    "max": 240.0,
                    "step": 0.1,
                    "tooltip": "Video frames per second.",
                }),
                "total_frames": ("INT", {
                    "default": 81,
                    "min": 1,
                    "max": 100000,
                    "step": 1,
                    "tooltip": "Total frames generated by one video pass.",
                }),
            },
        }

    CATEGORY = "AFL/Audio"
    RETURN_TYPES = ("INT", "FLOAT", "FLOAT", "STRING")
    RETURN_NAMES = ("loops", "audio_seconds", "clip_seconds", "info")
    FUNCTION = "calculate"

    def calculate(self, audio, fps, total_frames):
        sample_rate = int(audio["sample_rate"])
        if sample_rate <= 0:
            raise ValueError("audio sample_rate must be > 0")

        audio_frames = _get_audio_frames(audio)
        audio_seconds = float(audio_frames) / float(sample_rate)
        clip_seconds = float(total_frames) / float(fps)
        loops = max(1, int(math.ceil(audio_seconds / clip_seconds)))

        info = (
            f"audio_seconds={audio_seconds:.4f}, "
            f"clip_seconds={clip_seconds:.4f}, "
            f"loops={loops}"
        )
        return (loops, float(audio_seconds), float(clip_seconds), info)


NODE_CLASS_MAPPINGS = {
    "AFL:AudioLoopCalculator": AFLAudioLoopCalculator,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "AFL:AudioLoopCalculator": "AFL Audio Loop Calculator",
}
